---
title: "Salma Elshahawy <br> Curriculum vitae"
#date: "`r Sys.Date()`"
output:
  pagedown::html_paged:
    # change to true for a self-contained document, but it'll be a litte slower for Pandoc to render
    self_contained: false
    # CDS
    css: [css/one-column-paged.css, "https://use.fontawesome.com/releases/v5.7.2/css/all.css"]
    # offline
    #css: ["css/one-column-paged.css",  "fontawesome-free-5.8.1-web/css/all.css"]
    number_sections: false
links-to-footnotes: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(knitr)

#### cv entries #####
cv_entries <- readxl::read_xlsx("_cv_data/cv_entries.xlsx")

#### projects #####
projects <- readxl::read_xlsx("_cv_data/projects.xlsx")
```

<div class="grid-container">
<!-- top row -->
```{r summary, child = 'content/summary.Rmd'}
```

```{r contact-info, child = 'content/contact-info.Rmd'}
```

</div>

## Education {.education .nohead}
```{r}
cv_entries %>% 
  filter(type == 'education') %>% 
  mutate(what = str_c(what, ", ", where)) %>% 
  mutate(year = str_c(year_begin, " --- ", year_end)) %>% 
  select(year, what) %>% 
  kable()
```


## Projects {.nohead .publications .set-width}
```{r}
projects %>%
  filter(type == "data science") %>%
  mutate(title = ifelse(!is.na(url), str_c("<span class='work-title'>","[", title, "](", url, ")", "</span><br class='work-break'>",  "<br>", "</span><br class='work-break'>"), title)) %>% #turn title into link
  mutate(GitHub = ifelse(!is.na(GitHub), str_c("[GitHub-Repo](", GitHub, ")"), GitHub)) %>%
  select(title, short_title, GitHub, stack) %>%
  #mutate(title = str_c("<span style='text-decoration: underline'>", title, "</span>")) %>% #underline title

knitr::kable()
```

## Web development {.nohead .posters .set-width}
```{r}
projects %>%
  filter(type == "web development") %>%
  mutate(title = ifelse(!is.na(url), str_c("<span class='work-title'>","[", title, "](", url, ")", "</span><br class='work-break'>",  "<br>", "</span><br class='work-break'>"), title)) %>% #turn title into link
  mutate(GitHub = ifelse(!is.na(GitHub), str_c("[GitHub-Repo](", GitHub, ")"), GitHub)) %>%
  select(title, short_title, GitHub, stack) %>%
  #mutate(title = str_c("<span style='text-decoration: underline'>", title, "</span>")) %>% #underline title

knitr::kable()
```


<br class="pageBreak">

### Links
